name: Artifacts test

on: push

jobs:
  j1:
    name: job 1
    runs-on: ubuntu-latest
    
    steps:
      - name: generador archivo
        run: |
          echo "Archivo prueba, hola" >> test.log
      - name: subir Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

  j2:
    name: job 2
    runs-on: ubuntu-latest
    needs: j1

    steps:
      - name: Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: archivo-test
      - name: Cat file
        run: cat test.log