name: Deploy project

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    # se pueden crear servicios en local (crea contendores de docker)
    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379

    steps:
      # - name: Install redis
      #   run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      # - name: Test redis
      #   run: redis-cli -h localhost -p 6379 ping

      - name: Print Variable
        run: echo "${{ secrets.SECRET_VAR}}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd project-test-GITHUBACT && npm install

      - name: Run test
        run: cd project-test-GITHUBACT && npm run test